"""Add about_text column to Users model

Revision ID: 7ddcd9b17aa5
Revises: 9486d3d93594
Create Date: 2024-07-20 19:06:12.260438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ddcd9b17aa5'
down_revision = '9486d3d93594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about_text')

    # ### end Alembic commands ###