"""Add about_me column to Users

Revision ID: cfc3a5aae97c
Revises: 7ddcd9b17aa5
Create Date: 2024-07-20 19:41:14.963458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc3a5aae97c'
down_revision = '7ddcd9b17aa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.Text(), nullable=True))
        batch_op.drop_column('about_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_text', sa.TEXT(), nullable=True))
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
